MODEL:
  TYPE: generalized_wsl
  CONV_BODY: VGG16.add_VGG16_conv5_body_origin
  NUM_CLASSES: 21
  MASK_ON: False
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MOMENTUM: 0.9
  MAX_ITER: 100000
  STEPS: [0, 100000]
  WARM_UP_ITERS: 0
# SOLVER:
#   WEIGHT_DECAY: 0.0005
#   LR_POLICY: steps_with_lrs
#   BASE_LR: 0.001
#   GAMMA: 0.1
#   MOMENTUM: 0.9
#   MAX_ITER: 100000
#   STEPS: [0, 50000]
#   LRS: [0.001, 0.0001]
#   WARM_UP_ITERS: 0
FAST_RCNN:
  ROI_BOX_HEAD: wsl_heads.add_VGG16_roi_2fc_head
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: /home/chenzhiwei/Dataset/model/VGG_ILSVRC_16_layers.pkl
  DATASETS: ('voc_2007_train', 'voc_2007_val')
  PROPOSAL_FILES: ('detectron/datasets/data/mcg_voc_2007_train.pkl', 'detectron/datasets/data/mcg_voc_2007_val.pkl')
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 1500
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 2048
  FREEZE_CONV_BODY: True
  CROWD_FILTER_THRESH: 0.0
  SNAPSHOT_ITERS: 20000
TEST:
  DATASETS: ('voc_2007_test',)
  PROPOSAL_FILES: ('detectron/datasets/data/mcg_voc_2007_test.pkl',)
  PROPOSAL_LIMIT: 9999
  SCALE: 688
  MAX_SIZE: 2000
  NMS: 0.5
  BBOX_REG: False
  SCORE_THRESH: 0.000000001
  #DETECTIONS_PER_IM: 10000
  DETECTIONS_PER_IM: 100
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: 'SUM'
    COORD_HEUR: 'ID'
    H_FLIP: True
    SCALES: (480, 576, 864, 1200)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
OUTPUT_DIR: .
RNG_SEED: 11
PIXEL_MEANS: [[[103.939, 116.779, 123.68]]]
WSL:
  WSL_ON: True
  ITER_SIZE: 32
  DEBUG: False
  SAMPLE: True
  CSC: True
  CPG: True
  CPG_PRE_BLOB: 'mining_rois_pred'
  #CPG_PRE_BLOB: 'cls_prob'
  # CSC_MAX_ITER: 25000
  CSC_MAX_ITER: 12500
  CENTER_LOSS: True
  CENTER_LOSS_NUMBER: 5
  DILATION: 2
  MIN_ENTROPY_LOSS: False
MEMONGER: True
USE_NCCL: True
