MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 21
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.00001
  GAMMA: 0.1
  MAX_ITER: 37500
  STEPS: [0, 12500, 25000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0,)
  SCALES_PER_OCTAVE: 1
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
  BBOX_REG_WEIGHT: 0.0
  SOFTMAX: True
  INFERENCE_TH: 0.00001
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  #WEIGHTS: '/tmp/detectron-download-cache/ImageNetPretrained/MSRA/R-50.pkl'
  DATASETS: ('voc_2007_train', 'voc_2007_val')
  SCALES: (800,)
  MAX_SIZE: 1333
  RPN_STRADDLE_THRESH: -1  # default 0
  IMS_PER_BATCH: 2
TEST:
  DATASETS: ('voc_2007_test',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
  BBOX_REG: False
OUTPUT_DIR: .
WSL:
  WSL_ON: True
VIS: True
VIS_TH: 0.00001
