MODEL:
  TYPE: generalized_wsl
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 21
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0001
  GAMMA: 0.1
  MOMENTUM: 0.9
  MAX_ITER: 36000
  STEPS: [0, 24000, 32000]
  WARM_UP_ITERS: 0
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  #ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_BOX_HEAD: wsl_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('voc_2007_train', 'voc_2007_val')
<<<<<<< HEAD
  PROPOSAL_FILES: ('detectron/datasets/data/mcg_voc_2007_train.pkl', 'detectron/datasets/data/mcg_voc_2007_val.pkl')
=======
  PROPOSAL_FILES: ('detectron/datasets/data/proposal/mcg_voc_2007_train.pkl', 'detectron/datasets/data/proposal/mcg_voc_2007_val.pkl')
>>>>>>> ecf649754cb7431cdd0f6855abdb75fd36eb88ed
  SCALES: (480, 576, 688, 864, 1200)
  BATCH_SIZE_PER_IM: 2048
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 2048
  FREEZE_CONV_BODY: True
  CROWD_FILTER_THRESH: 0.0
  SNAPSHOT_ITERS: 5004
TEST:
  DATASETS: ('voc_2007_test',)
<<<<<<< HEAD
  PROPOSAL_FILES: ('detectron/datasets/data/mcg_voc_2007_test.pkl',)
=======
  PROPOSAL_FILES: ('detectron/datasets/data/proposal/mcg_voc_2007_test.pkl',)
>>>>>>> ecf649754cb7431cdd0f6855abdb75fd36eb88ed
  PROPOSAL_LIMIT: 2048
  SCALE: 688
  MAX_SIZE: 2000
  NMS: 0.5
  BBOX_REG: False
  SCORE_THRESH: 0.0000000001
  #DETECTIONS_PER_IM: 10000
  DETECTIONS_PER_IM: 100
  BBOX_AUG:
    ENABLED: False
    SCORE_HEUR: 'AVG'
    COORD_HEUR: 'AVG'
    H_FLIP: True
    SCALES: (480, 576, 864, 1200)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
OUTPUT_DIR: .
RNG_SEED: 2
WSL:
  WSL_ON: True
  ITER_SIZE: 32
  DILATION: 2
MEMONGER: True
VIS: True
VIS_TH: 0.1
USE_NCCL: True
