MODEL:
  TYPE: generalized_wsl
  CONV_BODY: VGG16.add_VGG16_conv5_body_origin
  #CONV_BODY: VGG16.add_VGG16_conv5_body_deeplab
  NUM_CLASSES: 21
  MASK_ON: False
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MOMENTUM: 0.9
  MAX_ITER: 35000
  STEPS: [0, 35000]
  WARM_UP_ITERS: 0
FAST_RCNN:
  ROI_BOX_HEAD: wsl_heads.add_VGG16_roi_2fc_head
  #ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
<<<<<<< HEAD
  #WEIGHTS: /home/shenyunhang/Dataset/model/pytorch/vgg16_pytorch.pkl
  WEIGHTS: /home/shenyunhang/Dataset/model/pytorch/vgg16_bn_pytorch.pkl
  DATASETS: ('voc_2007_train', 'voc_2007_val')
  PROPOSAL_FILES: ('detectron/datasets/data/mcg_voc_2007_train.pkl', 'detectron/datasets/data/mcg_voc_2007_val.pkl')
=======
  #WEIGHTS: model/pytorch/vgg16_pytorch.pkl
  WEIGHTS: model/pytorch/vgg16_bn_pytorch.pkl
  DATASETS: ('voc_2007_train', 'voc_2007_val')
  PROPOSAL_FILES: ('detectron/datasets/data/proposal/mcg_voc_2007_train.pkl', 'detectron/datasets/data/proposal/mcg_voc_2007_val.pkl')
>>>>>>> ecf649754cb7431cdd0f6855abdb75fd36eb88ed
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 2048
  FREEZE_CONV_BODY: True
  CROWD_FILTER_THRESH: 0.0
  SNAPSHOT_ITERS: 10000
TEST:
  DATASETS: ('voc_2007_test',)
<<<<<<< HEAD
  PROPOSAL_FILES: ('detectron/datasets/data/mcg_voc_2007_test.pkl',)
=======
  PROPOSAL_FILES: ('detectron/datasets/data/proposal/mcg_voc_2007_test.pkl',)
>>>>>>> ecf649754cb7431cdd0f6855abdb75fd36eb88ed
  PROPOSAL_LIMIT: 9999
  SCALE: 688
  MAX_SIZE: 2000
  NMS: 0.5
  BBOX_REG: False
  SCORE_THRESH: 0.000000001
  #DETECTIONS_PER_IM: 10000
  DETECTIONS_PER_IM: 100
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: 'SUM'
    COORD_HEUR: 'ID'
    H_FLIP: True
    SCALES: (480, 576, 864, 1200)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
OUTPUT_DIR: .
RNG_SEED: 11
PIXEL_MEANS: [[[0.485, 0.456, 0.406]]]
PIXEL_STDS: [[[0.229, 0.224, 0.225]]]
WSL:
  WSL_ON: True
  ITER_SIZE: 32
  DILATION: 2
  PTH_IMG: True
MEMONGER: True
VIS: True
VIS_TH: 0.1
USE_NCCL: True
