MODEL:
  TYPE: generalized_wsl
  CONV_BODY: ResNet18xp.add_ResNet18_conv5_body
  NUM_CLASSES: 21
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MOMENTUM: 0.9
  MAX_ITER: 35000
  STEPS: [0, 35000]
  WARM_UP_ITERS: 0
RESNETS:
  RES5_DILATION: 2
FPN:
  FPN_ON: True
  COARSEST_STRIDE: 1
  MULTILEVEL_ROIS: True
  ROI_CANONICAL_SCALE: 224
  ROI_CANONICAL_LEVEL: 4
  ROI_MAX_LEVEL: 4
  ROI_MIN_LEVEL: 2
  RPN_MAX_LEVEL: 4
  RPN_MIN_LEVEL: 2
# Finest level of the FPN pyramid
FAST_RCNN:
  ROI_BOX_HEAD: wsl_heads.add_ResNet_roi_2fc_head
  MLP_HEAD_DIM: 1024
  #ROI_BOX_HEAD: wsl_heads.add_ResNet_roi_0fc_head
  #ROI_BOX_HEAD: wsl_heads.add_roi_Xconv1fc_head
  #ROI_BOX_HEAD: wsl_heads.add_roi_Xconv_head
  #CONV_HEAD_DIM: 256
  #NUM_STACKED_CONVS: 2
  #ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: model/shenyunhang/resnet18x_model_99.pkl
  DATASETS: ('voc_2007_train', 'voc_2007_val')
  PROPOSAL_FILES: ('detectron/datasets/data/proposal/mcg_voc_2007_train.pkl', 'detectron/datasets/data/proposal/mcg_voc_2007_val.pkl')
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 1800
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 2048
  FREEZE_CONV_BODY: True
  CROWD_FILTER_THRESH: 0.0
  SNAPSHOT_ITERS: 10000
TEST:
  DATASETS: ('voc_2007_test',)
  PROPOSAL_FILES: ('detectron/datasets/data/proposal/mcg_voc_2007_test.pkl',)
  PROPOSAL_LIMIT: 9999
  SCALE: 688
  MAX_SIZE: 2000
  NMS: 0.5
  BBOX_REG: False
  SCORE_THRESH: 0.000000001
  #DETECTIONS_PER_IM: 10000
  DETECTIONS_PER_IM: 100
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: 'SUM'
    COORD_HEUR: 'ID'
    H_FLIP: True
    SCALES: (480, 576, 864, 1200)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
OUTPUT_DIR: .
RNG_SEED: 11
PIXEL_MEANS: [[[128.0, 128.0, 128.0]]]
PIXEL_STDS: [[[128.0, 128.0, 128.0]]]
WSL:
  WSL_ON: True
  ITER_SIZE: 32
  DILATION: 2
MEMONGER: True
VIS: True
VIS_TH: 0.1
USE_NCCL: True
DEDUP_BOXES: 0.0625
